<?php

namespace Opticity\GestionBundle\Repository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{
    public function findClient($id) {
        $qb = $this->createQueryBuilder('c')
            ->select('c');

        if (!empty($id)) {
            $qb->where('c.id in (:client_id)')
                ->setParameters([
                    'client_id' => $id
                ]);
        }

        $result = $qb->getQuery()
            ->getArrayResult();

        if (!empty($result)) {
            return [
                "client" => $result
            ];
        }
        return [];
    }
}
