<?php

namespace Opticity\GestionBundle\Repository;

/**
 * CommandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCommand($code) {
        $qb = $this->createQueryBuilder('c')
            ->select('c', 'cl', 'p')
            ->innerJoin('c.client', 'cl')
            ->innerJoin('c.produit', 'p');

        if (!empty($code)) {

            $qb->where('f.code in (:code)')
                ->setParameters([
                    'code' => $code
                ]);
        }

        $result = $qb->getQuery()
            ->getArrayResult();

        if (!empty($result)) {
            return [
                "command" => $result
            ];
        }
        return [
            "command" => []
        ];
    }
}
