<?php

namespace Opticity\GestionBundle\Repository;

/**
 * FournisseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FournisseurRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneOrAllFournisseur($code) {
        $qb = $this->createQueryBuilder('f')
            ->select('f');

        if (!empty($code)) {

            $qb->where('f.code in (:code)')
                ->setParameters([
                    'code' => $code
                ]);
        }

        $result = $qb->getQuery()
            ->getArrayResult();

        if (!empty($result)) {
            return [
                "fournisseur" => $result
            ];
        }
        return [
            "fournisseur" => []
        ];
    }
}
