<?php

namespace Opticity\GestionBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findProduct($code) {
        $qb = $this->createQueryBuilder('p')
            ->select('p');

        if (!empty($code)) {
            $qb->where('p.code in (:code_product)')
                ->setParameters([
                    'code_product' => $code
                ]);
        }

        $result = $qb->getQuery()
            ->getArrayResult();

        if (!empty($result)) {
            return [
                "product" => $result
            ];
        }
        return [];
    }
}
