opticity_gestion:
    resource: "@OpticityGestionBundle/Controller/"
    type:     annotation

app:
    resource: '@AppBundle/Controller/'
    type: annotation

login:
    path:     /login
    defaults: { _controller: OpticityGestionBundle:Security:login }